return {
  --     "catppuccin/nvim",
  --     lazy = false,
  --     priority = 1000,
  --     name = "catppuccin",
  --     opts = {
  --         flavour = "mocha", -- latte, frappe, macchiato, mocha
  --         background = { -- :h background
  --         light = "latte",
  --         dark = "mocha",
  --         },
  --         transparent_background = true,
  --         term_colors = true,
  --         styles = {
  --         comments = { "italic" },
  --         conditionals = { "italic" },
  --         loops = { "italic" },
  --         functions = { "italic" },
  --         keywords = { "italic" },
  --         strings = {},
  --         variables = {},
  --         numbers = {},
  --         booleans = {},
  --         properties = {},
  --         types = {},
  --         operators = {},
  --         },
  --         color_overrides = {
  --         mocha = {
  --             base = "#1E1E2E",
  --             mantle = "#181825",
  --             crust = "#11111B",
  --         },
  --         },
  --     },
}

